### ISSUE TITLE
Don't hardcode the drush constraint to a specific version

### ISSUE THREAD

**Issue by daften** [boedah/robo-drush#9]
The change here https://github.com/boedah/robo-drush/pull/8/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R26 will conflict with dependencies for Drupal 8.4, where drush 9 is required.

**Comment by daften** [comment]
When using a composer.json in tests, it should be a separate file from the main composer.json. See https://github.com/drupal-composer/drupal-scaffold/blob/master/tests/PluginTest.php for an example

**Comment by boedah** [comment]
@daften: as drush is only in require-dev, there should not be any problems with using robo-drush + Drupal 8.4 together.

Writing a new composer.json in a separate directory with an updated version before each test run would do the trick, yes.
